name: udp
description: Lightweight, efficient, and easy-to-use UDP library for Dart. Supports Unicast, Broadcast, Multicast and Loopback communications.
version: 3.0.3
homepage: https://github.com/xenoken/udp
repository: https://github.com/xenoken/udp
issue_tracker: https://github.com/xenoken/udp/issues
author: Ken Ekeoha <ekeohak@gmail.com>

environment:
  sdk: ">=2.12.3 <3.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.17.4
